[2025-10-09T16:49:24.194+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-09T16:49:24.201+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqlite_example_dag.insert_data manual__2025-10-09T16:49:19.404102+00:00 [queued]>
[2025-10-09T16:49:24.205+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqlite_example_dag.insert_data manual__2025-10-09T16:49:19.404102+00:00 [queued]>
[2025-10-09T16:49:24.206+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-09T16:49:24.218+0000] {taskinstance.py:2888} INFO - Executing <Task(SQLExecuteQueryOperator): insert_data> on 2025-10-09 16:49:19.404102+00:00
[2025-10-09T16:49:24.221+0000] {standard_task_runner.py:72} INFO - Started process 78 to run task
[2025-10-09T16:49:24.223+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sqlite_example_dag', 'insert_data', 'manual__2025-10-09T16:49:19.404102+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpc7vu3tzm']
[2025-10-09T16:49:24.224+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask insert_data
[2025-10-09T16:49:24.238+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-09T16:49:24.266+0000] {task_command.py:467} INFO - Running <TaskInstance: sqlite_example_dag.insert_data manual__2025-10-09T16:49:19.404102+00:00 [running]> on host 020cf4d88b8c
[2025-10-09T16:49:24.311+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sqlite_example_dag' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-09T16:49:19.404102+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-09T16:49:19.404102+00:00'
[2025-10-09T16:49:24.312+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-09T16:49:24.322+0000] {sql.py:266} INFO - Executing: INSERT INTO users (name, age) VALUES ('Alice', 30), ('Bob', 54), ('Tin', 80);
[2025-10-09T16:49:24.325+0000] {base.py:84} INFO - Retrieving connection 'sqlite_default'
[2025-10-09T16:49:24.368+0000] {base.py:84} INFO - Retrieving connection 'sqlite_default'
[2025-10-09T16:49:24.369+0000] {sql.py:509} INFO - Running statement: INSERT INTO users (name, age) VALUES ('Alice', 30), ('Bob', 54), ('Tin', 80);, parameters: None
[2025-10-09T16:49:24.370+0000] {sql.py:518} INFO - Rows affected: 3
[2025-10-09T16:49:24.378+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-09T16:49:24.379+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sqlite_example_dag, task_id=insert_data, run_id=manual__2025-10-09T16:49:19.404102+00:00, execution_date=20251009T164919, start_date=20251009T164924, end_date=20251009T164924
[2025-10-09T16:49:24.397+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-09T16:49:24.404+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T16:49:24.405+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
