[2025-10-17T18:58:21.973+0000] {processor.py:186} INFO - Started process (PID=26) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:58:21.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T18:58:21.976+0000] {logging_mixin.py:190} INFO - [2025-10-17T18:58:21.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:58:21.988+0000] {logging_mixin.py:190} INFO - [2025-10-17T18:58:21.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 48
    % s
    ^
SyntaxError: invalid syntax
[2025-10-17T18:58:21.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:58:22.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.055 seconds
[2025-10-17T18:58:52.349+0000] {processor.py:186} INFO - Started process (PID=31) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:58:52.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T18:58:52.353+0000] {logging_mixin.py:190} INFO - [2025-10-17T18:58:52.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:58:52.362+0000] {logging_mixin.py:190} INFO - [2025-10-17T18:58:52.361+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 48
    % s
    ^
SyntaxError: invalid syntax
[2025-10-17T18:58:52.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:58:52.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.059 seconds
[2025-10-17T18:59:23.075+0000] {processor.py:186} INFO - Started process (PID=36) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:59:23.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T18:59:23.079+0000] {logging_mixin.py:190} INFO - [2025-10-17T18:59:23.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:59:23.088+0000] {logging_mixin.py:190} INFO - [2025-10-17T18:59:23.087+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 48
    % s
    ^
SyntaxError: invalid syntax
[2025-10-17T18:59:23.089+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:59:23.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.059 seconds
[2025-10-17T18:59:53.301+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:59:53.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T18:59:53.304+0000] {logging_mixin.py:190} INFO - [2025-10-17T18:59:53.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:59:53.313+0000] {logging_mixin.py:190} INFO - [2025-10-17T18:59:53.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 48
    % s
    ^
SyntaxError: invalid syntax
[2025-10-17T18:59:53.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T18:59:53.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.057 seconds
[2025-10-17T19:00:10.264+0000] {processor.py:186} INFO - Started process (PID=46) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:00:10.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:00:10.267+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:00:10.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:00:11.214+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:00:11.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:00:11.217+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:00:11.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 1.009 seconds
[2025-10-17T19:00:41.879+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:00:41.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:00:41.882+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:00:41.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:00:42.734+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:00:42.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:00:42.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:00:42.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.898 seconds
[2025-10-17T19:01:13.074+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:01:13.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:01:13.077+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:01:13.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:01:13.913+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:01:13.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:01:13.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:01:13.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.879 seconds
[2025-10-17T19:01:44.131+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:01:44.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:01:44.134+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:01:44.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:01:44.983+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:01:44.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:01:44.984+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:01:45.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.890 seconds
[2025-10-17T19:02:15.293+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:02:15.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:02:15.295+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:02:15.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:02:16.114+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:02:16.108+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:02:16.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:02:16.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.870 seconds
[2025-10-17T19:02:46.447+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:02:46.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:02:46.449+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:02:46.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:02:47.283+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:02:47.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:02:47.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:02:47.322+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.880 seconds
[2025-10-17T19:03:17.588+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:03:17.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:03:17.590+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:03:17.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:03:18.399+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:03:18.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:03:18.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:03:18.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.860 seconds
[2025-10-17T19:03:48.771+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:03:48.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:03:48.774+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:03:48.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:03:49.605+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:03:49.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:03:49.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:03:49.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.862 seconds
[2025-10-17T19:04:19.951+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:04:19.951+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:04:19.953+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:04:19.953+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:04:20.784+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:04:20.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:04:20.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:04:20.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.864 seconds
[2025-10-17T19:04:51.221+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:04:51.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:04:51.224+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:04:51.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:04:52.134+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:04:52.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:04:52.135+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:04:52.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.937 seconds
[2025-10-17T19:05:22.523+0000] {processor.py:186} INFO - Started process (PID=176) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:05:22.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:05:22.526+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:05:22.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:05:23.433+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:05:23.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:05:23.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:05:23.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.960 seconds
[2025-10-17T19:05:53.593+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:05:53.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:05:53.596+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:05:53.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:05:54.495+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:05:54.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:05:54.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:05:54.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.953 seconds
[2025-10-17T19:06:24.870+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:06:24.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:06:24.873+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:06:24.873+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:06:25.704+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:06:25.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:06:25.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:06:25.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.876 seconds
[2025-10-17T19:06:56.080+0000] {processor.py:186} INFO - Started process (PID=215) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:06:56.081+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:06:56.083+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:06:56.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:06:56.896+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:06:56.890+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:06:56.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:06:56.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.857 seconds
[2025-10-17T19:07:27.263+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:07:27.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:07:27.266+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:07:27.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:07:28.100+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:07:28.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:07:28.101+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:07:28.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.866 seconds
[2025-10-17T19:07:58.470+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:07:58.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:07:58.473+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:07:58.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:07:59.314+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:07:59.305+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:07:59.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:07:59.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.893 seconds
[2025-10-17T19:08:29.632+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:08:29.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:08:29.635+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:08:29.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:08:30.538+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:08:30.530+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:08:30.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:08:30.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.934 seconds
[2025-10-17T19:09:00.687+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:09:00.687+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:09:00.689+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:09:00.689+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:09:01.590+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:09:01.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:09:01.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:09:01.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.945 seconds
[2025-10-17T19:09:31.738+0000] {processor.py:186} INFO - Started process (PID=280) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:09:31.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:09:31.741+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:09:31.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:09:32.681+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:09:32.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:09:32.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:09:32.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.973 seconds
[2025-10-17T19:10:03.042+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:10:03.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:10:03.045+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:10:03.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:10:03.908+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:10:03.902+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:10:03.909+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:10:03.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.903 seconds
[2025-10-17T19:10:34.375+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:10:34.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:10:34.378+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:10:34.377+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:10:35.231+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:10:35.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:10:35.233+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:10:35.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.920 seconds
[2025-10-17T19:11:05.462+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:11:05.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:11:05.465+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:11:05.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:11:06.280+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:11:06.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:11:06.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:11:06.322+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.864 seconds
[2025-10-17T19:11:36.534+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:11:36.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:11:36.537+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:11:36.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:11:37.458+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:11:37.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:11:37.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:11:37.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.986 seconds
[2025-10-17T19:12:07.644+0000] {processor.py:186} INFO - Started process (PID=345) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:12:07.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:12:07.646+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:12:07.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:12:08.511+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:12:08.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:12:08.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:12:08.584+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.944 seconds
[2025-10-17T19:12:38.759+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:12:38.760+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:12:38.762+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:12:38.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:12:39.651+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:12:39.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:12:39.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:12:39.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.942 seconds
[2025-10-17T19:13:10.106+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:13:10.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:13:10.109+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:13:10.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:13:10.984+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:13:10.975+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:13:10.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:13:11.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.930 seconds
[2025-10-17T19:13:41.340+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:13:41.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:13:41.343+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:13:41.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:13:42.190+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:13:42.181+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:13:42.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:13:42.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.897 seconds
[2025-10-17T19:14:12.631+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:14:12.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:14:12.635+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:14:12.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:14:13.491+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:14:13.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:14:13.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:14:13.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.888 seconds
[2025-10-17T19:14:43.867+0000] {processor.py:186} INFO - Started process (PID=410) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:14:43.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:14:43.870+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:14:43.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:14:44.741+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:14:44.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:14:44.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:14:44.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.909 seconds
[2025-10-17T19:15:15.164+0000] {processor.py:186} INFO - Started process (PID=423) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:15:15.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:15:15.167+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:15:15.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:15:16.067+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:15:16.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:15:16.070+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:15:16.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.950 seconds
[2025-10-17T19:15:46.474+0000] {processor.py:186} INFO - Started process (PID=436) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:15:46.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:15:46.477+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:15:46.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:15:47.334+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:15:47.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:15:47.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:15:47.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.903 seconds
[2025-10-17T19:16:17.776+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:16:17.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:16:17.779+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:17.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:16:18.655+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:18.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/anomaly_detection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/anomaly_detection.py", line 122, in <module>
    read_advertising_data >> check_stationarity >> calculate_forecast_range
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2025-10-17T19:16:18.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:16:18.690+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.919 seconds
[2025-10-17T19:16:30.152+0000] {processor.py:186} INFO - Started process (PID=458) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:16:30.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:16:30.155+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:30.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:16:31.020+0000] {processor.py:925} INFO - DAG(s) 'Anomaly_Detection_Daily' retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:16:31.222+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:31.221+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:Anomaly_Detection_Daily
[2025-10-17T19:16:31.242+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:31.242+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:Anomaly_Detection_Daily
[2025-10-17T19:16:31.259+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:31.259+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:Anomaly_Detection_Daily
[2025-10-17T19:16:31.289+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:31.289+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:Anomaly_Detection_Daily
[2025-10-17T19:16:31.308+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:31.307+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:Anomaly_Detection_Daily
[2025-10-17T19:16:31.328+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:31.328+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:Anomaly_Detection_Daily
[2025-10-17T19:16:31.346+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:31.346+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:Anomaly_Detection_Daily
[2025-10-17T19:16:31.347+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:31.347+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-17T19:16:31.359+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:31.358+0000] {dag.py:3262} INFO - Creating ORM DAG for Anomaly_Detection_Daily
[2025-10-17T19:16:31.360+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:16:31.359+0000] {dag.py:4180} INFO - Setting next_dagrun for Anomaly_Detection_Daily to None, run_after=None
[2025-10-17T19:16:31.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 1.252 seconds
[2025-10-17T19:17:02.028+0000] {processor.py:186} INFO - Started process (PID=543) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:17:02.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:17:02.032+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:17:02.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:17:02.960+0000] {processor.py:925} INFO - DAG(s) 'Anomaly_Detection_Daily' retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:17:02.991+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:17:02.991+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-17T19:17:03.006+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:17:03.006+0000] {dag.py:4180} INFO - Setting next_dagrun for Anomaly_Detection_Daily to None, run_after=None
[2025-10-17T19:17:03.041+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 1.018 seconds
[2025-10-17T19:17:28.778+0000] {processor.py:186} INFO - Started process (PID=556) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:17:28.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:17:28.781+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:17:28.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:17:29.646+0000] {processor.py:925} INFO - DAG(s) 'Anomaly_Detection_Daily' retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:17:29.671+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:17:29.671+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-17T19:17:29.682+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:17:29.682+0000] {dag.py:4180} INFO - Setting next_dagrun for Anomaly_Detection_Daily to None, run_after=None
[2025-10-17T19:17:29.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.954 seconds
[2025-10-17T19:19:26.533+0000] {processor.py:186} INFO - Started process (PID=648) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:19:26.534+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:19:26.536+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:19:26.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:19:27.315+0000] {processor.py:925} INFO - DAG(s) 'Anomaly_Detection_Daily' retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:19:27.347+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:19:27.347+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-17T19:19:27.362+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:19:27.362+0000] {dag.py:4180} INFO - Setting next_dagrun for Anomaly_Detection_Daily to None, run_after=None
[2025-10-17T19:19:27.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.895 seconds
[2025-10-17T19:19:57.930+0000] {processor.py:186} INFO - Started process (PID=661) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:19:57.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:19:57.932+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:19:57.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:19:58.697+0000] {processor.py:925} INFO - DAG(s) 'Anomaly_Detection_Daily' retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:19:58.719+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:19:58.718+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-17T19:19:58.730+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:19:58.730+0000] {dag.py:4180} INFO - Setting next_dagrun for Anomaly_Detection_Daily to None, run_after=None
[2025-10-17T19:19:58.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.847 seconds
[2025-10-17T19:20:27.672+0000] {processor.py:186} INFO - Started process (PID=674) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:20:27.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:20:27.674+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:20:27.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:20:28.462+0000] {processor.py:925} INFO - DAG(s) 'Anomaly_Detection_Daily' retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:20:28.501+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:20:28.500+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-17T19:20:28.517+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:20:28.517+0000] {dag.py:4180} INFO - Setting next_dagrun for Anomaly_Detection_Daily to None, run_after=None
[2025-10-17T19:20:28.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.914 seconds
[2025-10-17T19:22:49.755+0000] {processor.py:186} INFO - Started process (PID=767) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:22:49.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:22:49.757+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:22:49.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:22:50.543+0000] {processor.py:925} INFO - DAG(s) 'Anomaly_Detection_Daily' retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:22:50.568+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:22:50.568+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-17T19:22:50.581+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:22:50.581+0000] {dag.py:4180} INFO - Setting next_dagrun for Anomaly_Detection_Daily to None, run_after=None
[2025-10-17T19:22:50.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.879 seconds
[2025-10-17T19:23:21.498+0000] {processor.py:186} INFO - Started process (PID=780) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:23:21.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:23:21.500+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:23:21.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:23:22.296+0000] {processor.py:925} INFO - DAG(s) 'Anomaly_Detection_Daily' retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:23:22.325+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:23:22.325+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-17T19:23:22.339+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:23:22.338+0000] {dag.py:4180} INFO - Setting next_dagrun for Anomaly_Detection_Daily to None, run_after=None
[2025-10-17T19:23:22.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.892 seconds
[2025-10-17T19:23:53.398+0000] {processor.py:186} INFO - Started process (PID=793) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:23:53.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:23:53.400+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:23:53.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:23:54.210+0000] {processor.py:925} INFO - DAG(s) 'Anomaly_Detection_Daily' retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:23:54.247+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:23:54.247+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-17T19:23:54.263+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:23:54.263+0000] {dag.py:4180} INFO - Setting next_dagrun for Anomaly_Detection_Daily to None, run_after=None
[2025-10-17T19:23:54.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.943 seconds
[2025-10-17T19:24:25.382+0000] {processor.py:186} INFO - Started process (PID=806) to work on /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:24:25.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/anomaly_detection.py for tasks to queue
[2025-10-17T19:24:25.384+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:24:25.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:24:26.181+0000] {processor.py:925} INFO - DAG(s) 'Anomaly_Detection_Daily' retrieved from /opt/airflow/dags/anomaly_detection.py
[2025-10-17T19:24:26.216+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:24:26.216+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-17T19:24:26.231+0000] {logging_mixin.py:190} INFO - [2025-10-17T19:24:26.230+0000] {dag.py:4180} INFO - Setting next_dagrun for Anomaly_Detection_Daily to None, run_after=None
[2025-10-17T19:24:26.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/anomaly_detection.py took 0.907 seconds
