[2025-10-20T14:39:35.437+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-20T14:39:35.471+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Anomaly_Detection_Daily.store_results_for_model_diagnostics manual__2025-10-18T10:35:56.705718+00:00 [queued]>
[2025-10-20T14:39:35.496+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Anomaly_Detection_Daily.store_results_for_model_diagnostics manual__2025-10-18T10:35:56.705718+00:00 [queued]>
[2025-10-20T14:39:35.497+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-20T14:39:35.529+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): store_results_for_model_diagnostics> on 2025-10-18 10:35:56.705718+00:00
[2025-10-20T14:39:35.539+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Anomaly_Detection_Daily', 'store_results_for_model_diagnostics', 'manual__2025-10-18T10:35:56.705718+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/anomaly_detection.py', '--cfg-path', '/tmp/tmpfdkf0b0j']
[2025-10-20T14:39:35.540+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2216) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-20T14:39:35.542+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask store_results_for_model_diagnostics
[2025-10-20T14:39:35.542+0000] {standard_task_runner.py:72} INFO - Started process 2232 to run task
[2025-10-20T14:39:35.573+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-20T14:39:35.636+0000] {task_command.py:467} INFO - Running <TaskInstance: Anomaly_Detection_Daily.store_results_for_model_diagnostics manual__2025-10-18T10:35:56.705718+00:00 [running]> on host 9a3624a83b26
[2025-10-20T14:39:35.789+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Anomaly_Detection_Daily' AIRFLOW_CTX_TASK_ID='store_results_for_model_diagnostics' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T10:35:56.705718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-18T10:35:56.705718+00:00'
[2025-10-20T14:39:35.790+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-20T14:39:36.148+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-20T14:39:36.164+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-20T14:39:36.164+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Anomaly_Detection_Daily, task_id=store_results_for_model_diagnostics, run_id=manual__2025-10-18T10:35:56.705718+00:00, execution_date=20251018T103556, start_date=20251020T143935, end_date=20251020T143936
[2025-10-20T14:39:36.240+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-20T14:39:36.273+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T14:39:36.277+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
