[2025-10-10T08:01:32.716+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-10T08:01:32.727+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqlite_example_dag.insert_data manual__2025-10-10T08:01:27.557917+00:00 [queued]>
[2025-10-10T08:01:32.734+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqlite_example_dag.insert_data manual__2025-10-10T08:01:27.557917+00:00 [queued]>
[2025-10-10T08:01:32.735+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-10T08:01:32.756+0000] {taskinstance.py:2888} INFO - Executing <Task(SQLExecuteQueryOperator): insert_data> on 2025-10-10 08:01:27.557917+00:00
[2025-10-10T08:01:32.759+0000] {standard_task_runner.py:72} INFO - Started process 46 to run task
[2025-10-10T08:01:32.762+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sqlite_example_dag', 'insert_data', 'manual__2025-10-10T08:01:27.557917+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpjo9zp4z6']
[2025-10-10T08:01:32.763+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask insert_data
[2025-10-10T08:01:32.787+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-10T08:01:32.828+0000] {task_command.py:467} INFO - Running <TaskInstance: sqlite_example_dag.insert_data manual__2025-10-10T08:01:27.557917+00:00 [running]> on host cac94492a007
[2025-10-10T08:01:32.912+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sqlite_example_dag' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-10T08:01:27.557917+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-10T08:01:27.557917+00:00'
[2025-10-10T08:01:32.913+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-10T08:01:32.926+0000] {sql.py:266} INFO - Executing: INSERT INTO users (name, age) VALUES ('Alice', 30), ('Bob', 54), ('Tin', 80);
[2025-10-10T08:01:32.937+0000] {base.py:84} INFO - Retrieving connection 'sqlite_default'
[2025-10-10T08:01:32.993+0000] {base.py:84} INFO - Retrieving connection 'sqlite_default'
[2025-10-10T08:01:32.993+0000] {sql.py:509} INFO - Running statement: INSERT INTO users (name, age) VALUES ('Alice', 30), ('Bob', 54), ('Tin', 80);, parameters: None
[2025-10-10T08:01:32.994+0000] {sql.py:518} INFO - Rows affected: 3
[2025-10-10T08:01:33.006+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-10T08:01:33.006+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sqlite_example_dag, task_id=insert_data, run_id=manual__2025-10-10T08:01:27.557917+00:00, execution_date=20251010T080127, start_date=20251010T080132, end_date=20251010T080133
[2025-10-10T08:01:33.055+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-10T08:01:33.079+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-10T08:01:33.080+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
